### ISSUE TITLE
Running SuperTool in Gramps 5.2 beta throws console error

### ISSUE THREAD

**Issue by emyoulation** [Taapeli/isotammi-addons#18]
Error when launching the SuperTool from the Tools Selector dialog, launched from the Dashboard:

<small>

```
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.2.0\gramps\gen\plug\_manager.py", line 274, in load_plugin
    _module = self.import_plugin(pdata)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\GrampsAIO64-5.2.0\gramps\gen\plug\_manager.py", line 308, in import_plugin
    module = __import__(pdata.mod_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\gramps\gramps52\plugins\SuperTool\SuperTool.py", line 103, in <module>
    pp(a)
    ^^
NameError: name 'pp' is not defined

```

</small>

**Comment by kkujansuu** [comment]
Fixed in version 1.3.3
