### ISSUE TITLE
error in console while opening an empty db

### ISSUE THREAD

**Issue by patlx** [Taapeli/isotammi-addons#2]
Hi,

FYI I've got the following console message while opening a new database I just created (I was not using ST):

Warning: DbState: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gen\utils\callback.py", line 405, in emit
    fn(*args)
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\SuperTool\SuperTool.py", line 750, in db_changed
    self.select_category()
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\SuperTool\SuperTool.py", line 1206, in select_category
    self.category = supertool_utils.get_category_info(self.db, self.category_name)
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\SuperTool\supertool_utils.py", line 125, in get_category_info
    info.commitfunc = db.commit_event
AttributeError: 'DummyDb' object has no attribute 'commit_event'

**Comment by kkujansuu** [comment]
Thanks. I try to fix this in the next version. As far as I can see this does not affect execution - it is only a message that appears on the console.
